### ISSUE TITLE
Add basic auth for helpscout widget authentication

### ISSUE THREAD

**Issue by Santei** [onaio/milia#30]
Help scout uses HTTP basic auth to authenticate its API.

**Comment by pld** [comment]
What specifically would this involved adding to milia? Since this is not specific to the Ona API it's quite likely that it wouldn't be appropriate in milia. You can use the clj-http library together, or the http calling wrappers in milia to call the helpscout API. Both of those support HTTP BasicAuth

**Comment by Santei** [comment]
@pld Cool. It makes sense that way.Opted to used clj-http library.
